// Copyright (C) 2018 Dennis Tang. All rights reserved.
//
// This file is part of Balanced Field Length.
//
// Balanced Field Length is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.BalancedFieldLength.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.BalancedFieldLength.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspect ratio [-].
        /// </summary>
        internal static string AircraftData_AspectRatio_DisplayName {
            get {
                return ResourceManager.GetString("AircraftData_AspectRatio_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lift coefficient gradient [-/rad].
        /// </summary>
        internal static string AircraftData_LiftCoefficientGradient_DisplayName {
            get {
                return ResourceManager.GetString("AircraftData_LiftCoefficientGradient_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum pitch angle gradient [deg].
        /// </summary>
        internal static string AircraftData_MaximumPitchAngle_DisplayName {
            get {
                return ResourceManager.GetString("AircraftData_MaximumPitchAngle_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum lift coefficient [-].
        /// </summary>
        internal static string AircraftData_MaximumumLiftCoeffcient_DisplayName {
            get {
                return ResourceManager.GetString("AircraftData_MaximumumLiftCoeffcient_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oswald factor [-].
        /// </summary>
        internal static string AircraftData_OswaldFactor_DisplayName {
            get {
                return ResourceManager.GetString("AircraftData_OswaldFactor_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pitch angle gradient [deg/s].
        /// </summary>
        internal static string AircraftData_PitchAngleGradient_DisplayName {
            get {
                return ResourceManager.GetString("AircraftData_PitchAngleGradient_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest drag coefficient [-].
        /// </summary>
        internal static string AircraftData_RestDragCoefficient_DisplayName {
            get {
                return ResourceManager.GetString("AircraftData_RestDragCoefficient_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest drag coefficient, with engine failure [-].
        /// </summary>
        internal static string AircraftData_RestDragCoefficientWithEngineFailure_DisplayName {
            get {
                return ResourceManager.GetString("AircraftData_RestDragCoefficientWithEngineFailure_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll resistance coefficient [-].
        /// </summary>
        internal static string AircraftData_RollResistanceCoefficient_DisplayName {
            get {
                return ResourceManager.GetString("AircraftData_RollResistanceCoefficient_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll resistance coefficient, with brakes applied [-].
        /// </summary>
        internal static string AircraftData_RollResistanceWithBrakesCoefficient_DisplayName {
            get {
                return ResourceManager.GetString("AircraftData_RollResistanceWithBrakesCoefficient_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take off weight [kN].
        /// </summary>
        internal static string AircraftData_TakeOffWeight_DisplayName {
            get {
                return ResourceManager.GetString("AircraftData_TakeOffWeight_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wing surface area [m²].
        /// </summary>
        internal static string AircraftData_WingSurfaceArea_DisplayName {
            get {
                return ResourceManager.GetString("AircraftData_WingSurfaceArea_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero lift angle of attack [deg].
        /// </summary>
        internal static string AircraftData_ZeroLiftAngleOfAttack_DisplayName {
            get {
                return ResourceManager.GetString("AircraftData_ZeroLiftAngleOfAttack_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag properties.
        /// </summary>
        internal static string AircraftDataTabView_Drag_properties_DisplayName {
            get {
                return ResourceManager.GetString("AircraftDataTabView_Drag_properties_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lift properties.
        /// </summary>
        internal static string AircraftDataTabView_Lift_properties_DisplayName {
            get {
                return ResourceManager.GetString("AircraftDataTabView_Lift_properties_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takeoff properties.
        /// </summary>
        internal static string AircraftDataTabView_Take_off_properties_DisplayName {
            get {
                return ResourceManager.GetString("AircraftDataTabView_Take_off_properties_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft data.
        /// </summary>
        internal static string AircraftDataTabViewModel_TabName {
            get {
                return ResourceManager.GetString("AircraftDataTabViewModel_TabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of failed engines.
        /// </summary>
        internal static string EngineData_NrOfFailedEngines_DisplayName {
            get {
                return ResourceManager.GetString("EngineData_NrOfFailedEngines_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of engines.
        /// </summary>
        internal static string EngineData_NumberOfEngines_DisplayName {
            get {
                return ResourceManager.GetString("EngineData_NumberOfEngines_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thrust per engine [kN].
        /// </summary>
        internal static string EngineData_ThrustPerEngine_DisplayName {
            get {
                return ResourceManager.GetString("EngineData_ThrustPerEngine_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total thrust [kN].
        /// </summary>
        internal static string EngineData_TotalThrust_DisplayName {
            get {
                return ResourceManager.GetString("EngineData_TotalThrust_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine data.
        /// </summary>
        internal static string EngineSettingsTabViewModel_TabName {
            get {
                return ResourceManager.GetString("EngineSettingsTabViewModel_TabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Density [kg/m³].
        /// </summary>
        internal static string GeneralSimulationSettings_Density_DisplayName {
            get {
                return ResourceManager.GetString("GeneralSimulationSettings_Density_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End velocity [m/s].
        /// </summary>
        internal static string GeneralSimulationSettings_EndFailureVelocity_DisplayName {
            get {
                return ResourceManager.GetString("GeneralSimulationSettings_EndFailureVelocity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravitational acceleration [m/s²].
        /// </summary>
        internal static string GeneralSimulationSettings_GravitationalAcceleration_DisplayName {
            get {
                return ResourceManager.GetString("GeneralSimulationSettings_GravitationalAcceleration_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of iterations.
        /// </summary>
        internal static string GeneralSimulationSettings_MaximumNumberOfIterations_DisplayName {
            get {
                return ResourceManager.GetString("GeneralSimulationSettings_MaximumNumberOfIterations_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time step [s].
        /// </summary>
        internal static string GeneralSimulationSettings_TimeStep_DisplayName {
            get {
                return ResourceManager.GetString("GeneralSimulationSettings_TimeStep_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment Settings.
        /// </summary>
        internal static string GeneralSimulationSettingsTabView_Environment_properties_DisplayName {
            get {
                return ResourceManager.GetString("GeneralSimulationSettingsTabView_Environment_properties_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration scheme.
        /// </summary>
        internal static string GeneralSimulationSettingsTabView_IntegrationScheme_DisplayName {
            get {
                return ResourceManager.GetString("GeneralSimulationSettingsTabView_IntegrationScheme_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Euler.
        /// </summary>
        internal static string GeneralSimulationSettingsTabView_IntegrationScheme_Euler_DisplayName {
            get {
                return ResourceManager.GetString("GeneralSimulationSettingsTabView_IntegrationScheme_Euler_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numerical simulation settings.
        /// </summary>
        internal static string GeneralSimulationSettingsTabView_Numerical_settings_properties_DisplayName {
            get {
                return ResourceManager.GetString("GeneralSimulationSettingsTabView_Numerical_settings_properties_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulation Settings.
        /// </summary>
        internal static string GeneralSimulationSettingsTabViewModel_TabName {
            get {
                return ResourceManager.GetString("GeneralSimulationSettingsTabViewModel_TabName", resourceCulture);
            }
        }
    }
}
