//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.BalancedFieldLength.KernelWrapper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.BalancedFieldLength.KernelWrapper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End failure velocity must be larger than 0..
        /// </summary>
        internal static string BalancedFieldLengthCalculationModule_ValidationMessage_End_failure_velocity_must_be_larger_than_Zero {
            get {
                return ResourceManager.GetString("BalancedFieldLengthCalculationModule_ValidationMessage_End_failure_velocity_must_" +
                        "be_larger_than_Zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Density is invalid..
        /// </summary>
        internal static string BalancedFieldLengthCalculationModule_ValidationMessage_Invalid_Density {
            get {
                return ResourceManager.GetString("BalancedFieldLengthCalculationModule_ValidationMessage_Invalid_Density", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravitational acceleration is invalid..
        /// </summary>
        internal static string BalancedFieldLengthCalculationModule_ValidationMessage_Invalid_GravitationalAcceleration {
            get {
                return ResourceManager.GetString("BalancedFieldLengthCalculationModule_ValidationMessage_Invalid_GravitationalAccel" +
                        "eration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of failed engines is invalid..
        /// </summary>
        internal static string BalancedFieldLengthCalculationModule_ValidationMessage_Invalid_NrOfFailedEngines {
            get {
                return ResourceManager.GetString("BalancedFieldLengthCalculationModule_ValidationMessage_Invalid_NrOfFailedEngines", resourceCulture);
            }
        }
    }
}
