// Copyright (C) 2018 Dennis Tang. All rights reserved.
//
// This file is part of Balanced Field Length.
//
// Balanced Field Length is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simulator.Calculator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Simulator.Calculator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot determine crossing from a collection containing 0 or 1 item..
        /// </summary>
        internal static string BalancedFieldLengthCalculator_Cannot_determine_crossing_from_empty_or_single_item_collection {
            get {
                return ResourceManager.GetString("BalancedFieldLengthCalculator_Cannot_determine_crossing_from_empty_or_single_item" +
                        "_collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outputs cannot contain duplicate definitions for failure speed {0}..
        /// </summary>
        internal static string BalancedFieldLengthCalculators_Outputs_cannot_contain_duplicate_definitions_for_FailureSpeed_0 {
            get {
                return ResourceManager.GetString("BalancedFieldLengthCalculators_Outputs_cannot_contain_duplicate_definitions_for_F" +
                        "ailureSpeed_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation converged before failure occurred..
        /// </summary>
        internal static string DistanceCalculator_Calculation_converged_before_failure {
            get {
                return ResourceManager.GetString("DistanceCalculator_Calculation_converged_before_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation did not converge..
        /// </summary>
        internal static string DistanceCalculator_No_calculation_convergence {
            get {
                return ResourceManager.GetString("DistanceCalculator_No_calculation_convergence", resourceCulture);
            }
        }
    }
}
