name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  build_directory: ./BalancedFieldLength/ 

jobs:
  setup:
    name: Setup environment
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

  build_and_test:
    name: Build and test application
    steps:
    - name: Restore dependencies
      run: dotnet restore $env:build_directory --verbosity normal

    - name: Build Solution
      run: dotnet build $env:build_directory --no-restore

    - name: Run UnitTests
      run: dotnet test $env:build_directory --no-build --logger GitHubActions