name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  build_directory: ./BalancedFieldLength/ 

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
  
  test:
    - name: Setup .NET environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        
    - name: Restore dependencies
      run: dotnet restore $env:build_directory --verbosity normal
    
    - name: Build Solution
      run: dotnet build $env:build_directory --no-restore
    
    - name: Run UnitTests
      run: dotnet test $env:build_directory --no-build --logger:nunit
    
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1.7
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        files: TestResults/**/*.xml